import "server-only";
import {
  applyConfig,
  caddyfileDrift,
  caddyRunning,
  cleanConfig,
  configRev,
  readCaddyfile,
  readHistoryRoutes,
  renderCaddyfile,
  tryReadConfig,
  type RoutesConfig,
} from "../caddy/routes";
import { AppError } from "../errors";
import { audit } from "../audit";
import { publish } from "../events";
import { invalidateApps } from "../docker/apps";
import type { User } from "../auth/users";
import { describeConfig, describeChanges, routeWarnings } from "./routes-meta";
import { invalidateStatus, NOT_CONFIGURED } from "./status";
import { invalidateExposure } from "./exposure";
import { syncChatCertificates } from "./xmpp-certs";
import type { DriftInfo, RoutesResponse, RoutesSaveResponse } from "@/lib/network-types";

/**
 * Saving public addresses. Optimistic concurrency: the client sends the `rev` it loaded; if routes.json
 * changed since (another tab, the admin by hand, another tool) the save is refused with 409 and the
 * current rev, so nothing is silently clobbered. Saves are serialised in-process.
 */

let chain: Promise<unknown> = Promise.resolve();
function serial<T>(fn: () => Promise<T>): Promise<T> {
  const next = chain.then(fn, fn);
  chain = next.catch(() => undefined);
  return next;
}

export function currentConfig(): RoutesConfig {
  const cfg = tryReadConfig();
  if (!cfg) throw NOT_CONFIGURED();
  return cfg;
}

export async function routesResponse(): Promise<RoutesResponse> {
  const cfg = currentConfig();
  const [meta, running] = await Promise.all([describeConfig(cfg), caddyRunning()]);
  const drift = caddyfileDrift(cfg);
  return { config: cfg, rev: configRev(cfg), drift, driftInfo: drift ? driftInfo(cfg) : null, caddyRunning: running, ...meta };
}

/**
 * What differs between the Caddyfile on disk and Gluon's version, in terms a person can act on:
 * who wrote it (its header usually says, e.g. the older Domains app) and whether anything other
 * than comments differs.
 */
export function driftInfo(cfg: RoutesConfig): DriftInfo {
  let disk = "";
  try {
    disk = readCaddyfile();
  } catch {
    return { writer: null, settingLines: 0, sample: [] };
  }
  const writer = (disk.split("\n", 1)[0] ?? "").match(/generated by ((?:the )?[A-Za-z][\w .-]{1,40}?)(?:\s*[(.,\n]|$)/i)?.[1]?.trim() ?? null;
  const settings = (text: string) =>
    text
      .split("\n")
      .map((l) => l.replace(/\s+#.*$/, "").trim())
      .filter((l) => l && !l.startsWith("#"));
  const mine = settings(renderCaddyfile(cfg));
  const theirs = settings(disk);
  const count = (xs: string[]) => xs.reduce((m, x) => m.set(x, (m.get(x) ?? 0) + 1), new Map<string, number>());
  const a = count(mine);
  const b = count(theirs);
  const differ: string[] = [];
  for (const [line, n] of b) for (let i = a.get(line) ?? 0; i < n; i++) differ.push(line);
  let missing = 0;
  for (const [line, n] of a) missing += Math.max(0, n - (b.get(line) ?? 0));
  return { writer: writer && !/^gluon$/i.test(writer) ? writer : null, settingLines: Math.max(differ.length, missing), sample: differ.slice(0, 3) };
}

function staleError(current: RoutesConfig) {
  return new AppError(
    "stale",
    "The public addresses changed since you opened this page (in another tab, or by hand). Reload to see the latest, then make your change again.",
    409,
    { rev: configRev(current) },
  );
}

interface Where {
  ip: string;
  zone: string;
}

async function save(user: User, where: Where, rev: string, raw: { routes: unknown[]; fallback?: RoutesConfig["fallback"] }, reason: string, action: string, summaryPrefix: string): Promise<RoutesSaveResponse> {
  return serial(async () => {
    const current = currentConfig();
    if (configRev(current) !== rev) throw staleError(current);
    let next: RoutesConfig;
    try {
      next = cleanConfig(raw, current);
    } catch (e) {
      audit(user, { action, summary: `${summaryPrefix} (rejected: ${(e as Error).message})`, target: current.base_domain, outcome: "failed" }, where);
      throw e;
    }
    const changes = describeChanges(current, next);
    let saved: RoutesConfig;
    try {
      saved = await applyConfig(next, reason);
    } catch (e) {
      audit(user, { action, summary: `${summaryPrefix}: failed (${(e as Error).message})`, target: current.base_domain, detail: { changes }, outcome: "failed" }, where);
      throw e;
    }
    const warnings = await routeWarnings(saved, current).catch(() => []);
    audit(
      user,
      {
        action,
        summary: `${summaryPrefix}: ${changes.charAt(0).toLowerCase()}${changes.slice(1)}`,
        target: saved.base_domain,
        detail: { changes, warnings: warnings.filter((w) => w.isNew).map((w) => w.message), rev: configRev(saved) },
      },
      where,
    );
    invalidateApps();
    invalidateStatus();
    invalidateExposure();
    publish("network.routes", { rev: configRev(saved) });
    if (saved.routes.some((r) => r.type === "subdomain" && r.xmpp?.cert_sync)) {
      // Now for a domain Caddy already has; again once a new name has had time to get one.
      const run = () => void syncChatCertificates().then(invalidateStatus).catch(() => undefined);
      run();
      setTimeout(run, 90_000).unref?.();
    }
    const meta = await describeConfig(saved);
    return { config: saved, rev: configRev(saved), drift: caddyfileDrift(saved), warnings, summary: changes, ...meta };
  });
}

export function saveRoutes(user: User, where: Where, body: { rev: string; routes: unknown[]; fallback?: RoutesConfig["fallback"] }) {
  return save(user, where, body.rev, { routes: body.routes, fallback: body.fallback }, `Saved by ${user.username} in Gluon`, "network.routes.save", "Changed public addresses");
}

export function restoreRoutes(user: User, where: Where, body: { id: string; rev: string }) {
  const snap = readHistoryRoutes(body.id);
  if (!Array.isArray(snap.routes)) throw new AppError("bad_snapshot", "That snapshot doesn't contain any addresses, so it can't be restored.", 400);
  return save(user, where, body.rev, { routes: snap.routes, fallback: snap.fallback }, `Restored snapshot ${body.id} by ${user.username} in Gluon`, "network.routes.restore", `Restored public addresses from ${body.id}`);
}

/**
 * Point every public address (and the fallback) that names app `from` at app `to`, after Gluon
 * moves an app. Goes through the same checked, audited save as the Network page. Returns how many
 * addresses changed; 0 (and no save) when none name the app.
 */
export async function reassignRouteApp(user: User, where: Where, from: string, to: string): Promise<number> {
  const current = currentConfig();
  const ids = current.routes.filter((r) => r.app === from).map((r) => r.id);
  const fallback = current.fallback?.app === from;
  if (!ids.length && !fallback) return 0;
  const routes = current.routes.map((r) => (r.app === from ? { ...r, app: to } : r));
  await save(user, where, configRev(current), { routes, fallback: fallback ? { ...current.fallback, app: to } : current.fallback }, `Moved ${from} to ${to} in Gluon`, "network.routes.save", `Pointed public addresses at ${to}`);
  return ids.length + (fallback ? 1 : 0);
}
