import "server-only";
import fs from "node:fs";
import path from "node:path";
import http from "node:http";
import crypto from "node:crypto";
import { AppError } from "../errors";

/**
 * Public addresses (Caddy). Source of truth is routes.json next to the generated Caddyfile in
 * ~/proxy/caddy (mounted at /proxy-caddy). Every save renders a Caddyfile, loads it into Caddy via
 * its admin unix socket (atomic; Caddy keeps the old config on error), then persists both files.
 * Format-compatible with the original Domains app.
 */

export const CADDY_DIR = (process.env.GLUON_CADDY_DIR ?? process.env.TEND_CADDY_DIR) ?? "/proxy-caddy";
export const ADMIN_SOCKET = (process.env.GLUON_CADDY_SOCKET ?? process.env.TEND_CADDY_SOCKET) ?? "/run/caddy/admin.sock";
const ROUTES_FILE = path.join(CADDY_DIR, "routes.json");
const CADDYFILE = path.join(CADDY_DIR, "Caddyfile");
const HISTORY_DIR = path.join(CADDY_DIR, "history");
const HISTORY_KEEP = 40;
export const THIS_SERVER = "host.docker.internal";

export interface Backend {
  host: string;
  port: number;
  tls: boolean;
}

interface Base {
  id: string;
  name: string;
  enabled: boolean;
  app?: string;
  note?: string;
}
/** Paths on a subdomain served by a different backend (e.g. an app's admin behind another login). */
export interface ExtraPaths {
  paths: string[];
  backend: Backend;
  note?: string;
}
export interface SubdomainRoute extends Base {
  type: "subdomain";
  host: string;
  backend: Backend;
  only_paths?: string[];
  extra_paths?: ExtraPaths[];
  /** An XMPP chat server: `host` is its domain, `backend` its client (c2s) port. */
  xmpp?: XmppSettings;
  /** The whole host redirects here (keeping the path); `backend` is then unused. */
  redirect_to?: string;
}

/** A short link on the base domain, or a whole subdomain that redirects. */
export function isRedirect(r: Route | null | undefined): r is RedirectRoute | (SubdomainRoute & { redirect_to: string }) {
  return !!r && (r.type === "redirect" || (r.type === "subdomain" && !!r.redirect_to));
}
export interface XmppSettings {
  s2s_port: number | null;
  http_port: number | null;
  cert_sync: { container: string; dir: string } | null;
}

export const XMPP_C2S_PORT = 5222;
export const XMPP_S2S_PORT = 5269;
export interface PathRoute extends Base {
  type: "path";
  path: string;
  backend: Backend;
  strip_prefix: boolean;
}
export interface RedirectRoute extends Base {
  type: "redirect";
  path: string;
  target: string;
}
export type Route = SubdomainRoute | PathRoute | RedirectRoute;

export interface RoutesConfig {
  base_domain: string;
  fallback: { name: string; app?: string | null; backend: Backend };
  routes: Route[];
  updated?: string;
}

export function readConfig(): RoutesConfig {
  const raw = JSON.parse(fs.readFileSync(ROUTES_FILE, "utf8")) as RoutesConfig;
  return raw;
}

export function tryReadConfig(): RoutesConfig | null {
  try {
    return readConfig();
  } catch {
    return null;
  }
}

export function configRev(cfg: RoutesConfig): string {
  return crypto.createHash("sha256").update(stableStringify({ base_domain: cfg.base_domain, fallback: cfg.fallback, routes: cfg.routes })).digest("hex").slice(0, 16);
}

function stableStringify(v: unknown): string {
  if (Array.isArray(v)) return `[${v.map(stableStringify).join(",")}]`;
  if (v && typeof v === "object") {
    return `{${Object.keys(v as object)
      .sort()
      .map((k) => `${JSON.stringify(k)}:${stableStringify((v as Record<string, unknown>)[k])}`)
      .join(",")}}`;
  }
  return JSON.stringify(v);
}

/** Public URL for a route. */
export function routeUrl(cfg: RoutesConfig, r: Route): string {
  return r.type === "subdomain" ? `https://${r.host}` : `https://${cfg.base_domain}${r.path}`;
}

// ---------------------------------------------------------------- rendering

const HEAD = `# Caddy config for __BASE__, generated by Gluon (Network → Public addresses).
#
# Do not edit by hand: the next save in Gluon overwrites this file (the previous
# copy goes to ./history). Routes live in ./routes.json.
#
# Backends on this host are reached via host.docker.internal:<host port>.
# Only hostnames/paths listed here are reachable from the internet.
{
	# Local-only admin API on a unix socket shared with Gluon, which uses it to
	# apply changes without downtime. Nothing listens on :2019.
	admin unix//run/caddy/admin.sock

	servers {
		# __BASE__ is proxied by Cloudflare. Trust its ranges
		# (https://www.cloudflare.com/ips/) so logs and backends see the real
		# visitor IP instead of a Cloudflare edge address.
		trusted_proxies static 173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 141.101.64.0/18 108.162.192.0/18 190.93.240.0/20 188.114.96.0/20 197.234.240.0/22 198.41.128.0/17 162.158.0.0/15 104.16.0.0/13 104.24.0.0/14 172.64.0.0/13 131.0.72.0/22 2400:cb00::/32 2606:4700::/32 2803:f800::/32 2405:b500::/32 2405:8100::/32 2a06:98c0::/29 2c0f:f248::/32
		client_ip_headers CF-Connecting-IP X-Forwarded-For
	}
}

(common) {
	encode zstd gzip
	header {
		Strict-Transport-Security "max-age=31536000"
		X-Content-Type-Options "nosniff"
		Referrer-Policy "strict-origin-when-cross-origin"
		-Server
	}
	log {
		output stdout
		format json
	}
}
`;

const commentSafe = (t: string) => t.replace(/[^\w .,:;&()'/+*?!-]/g, "").slice(0, 80);

function wrap(text: string, width: number): string[] {
  const lines: string[] = [];
  let cur = "";
  for (const w of text.split(/\s+/).filter(Boolean)) {
    if (cur && cur.length + 1 + w.length > width) {
      lines.push(cur);
      cur = w;
    } else cur = cur ? `${cur} ${w}` : w;
  }
  return cur ? [...lines, cur] : lines;
}
const noteLines = (r: Route, prefix: string) => (r.note ? wrap(r.note, 76).map((l) => `${prefix}# ${commentSafe(l)}`) : []);

function backendLines(b: Backend, indent: number): string[] {
  const t = "\t".repeat(indent);
  const addr = `${b.host}:${b.port}`;
  if (b.tls) return [`${t}reverse_proxy https://${addr} {`, `${t}\ttransport http {`, `${t}\t\ttls_insecure_skip_verify`, `${t}\t}`, `${t}}`];
  return [`${t}reverse_proxy ${addr}`];
}

export const coveredByWildcard = (host: string, base: string) => host.endsWith(`.${base}`) && !host.slice(0, -base.length - 1).includes(".");

/**
 * [port, url] for dashboard app tiles: each backend port on this server with a fully published
 * subdomain. Routes limited to some paths are left out, since the tile would open a page the
 * route doesn't publish. First route wins.
 */
/**
 * Ports on this server that people on the internet reach, each with one address that sends them
 * there ("umbrel.example.com/admin"). Routes that are off or only redirect don't count.
 */
export function publicPorts(cfg: RoutesConfig): Map<number, string> {
  const out = new Map<number, string>();
  const add = (b: Backend, where: string) => {
    if (b.host === THIS_SERVER && !out.has(b.port)) out.set(b.port, where);
  };
  for (const r of cfg.routes) {
    if (r.enabled === false || isRedirect(r)) continue;
    const where = routeUrl(cfg, r).replace(/^https?:\/\//, "").replace(/\/$/, "");
    add(r.backend, r.type === "subdomain" && r.only_paths?.length ? `${where}${r.only_paths[0]!.replace(/\/?\*$/, "")}` : where);
    if (r.type === "subdomain") for (const x of r.extra_paths ?? []) add(x.backend, `${r.host}${x.paths[0]?.replace(/\/?\*$/, "") ?? ""}`);
  }
  add(cfg.fallback.backend, cfg.base_domain);
  return out;
}

export function appLinks(routes: Route[]): [number, string][] {
  const links = new Map<number, string>();
  for (const r of routes) {
    if (r.type !== "subdomain" || r.redirect_to) continue;
    if (!r.only_paths?.length && r.backend.host === THIS_SERVER && !links.has(r.backend.port)) {
      links.set(r.backend.port, `https://${r.host}`);
    }
    for (const x of r.extra_paths ?? []) {
      if (x.backend.host === THIS_SERVER && !links.has(x.backend.port)) links.set(x.backend.port, `https://${r.host}`);
    }
  }
  return [...links.entries()].sort((a, b) => a[0] - b[0]);
}

export function renderCaddyfile(cfg: RoutesConfig): string {
  const base = cfg.base_domain;
  const routes = cfg.routes.filter((r) => r.enabled !== false);
  const out: string[] = [HEAD.replaceAll("__BASE__", base)];
  const paths = routes
    .filter((r): r is PathRoute | RedirectRoute => r.type !== "subdomain")
    .sort((a, b) => b.path.length - a.path.length || a.path.localeCompare(b.path));
  out.push("# Proxied through Cloudflare (orange cloud): hides this network's IP, but");
  out.push("# uploads are capped at 100 MB and video streaming breaks Cloudflare's ToS.");
  out.push(`${base} {`, "\timport common", "");
  // CasaOS's /js/custom.js and Umbrel's /tile-links.js load this map so app tiles opened on the
  // public domain go to each app's public address instead of the LAN address:port.
  const links = appLinks(routes)
    .map(([port, url]) => `[${port}, "${url}"]`)
    .join(", ");
  const tileMap = [
    "\thandle /_domains/app-links.js {",
    '\t\theader Content-Type "text/javascript; charset=utf-8"',
    `\t\trespond \`window.__casaosAppLinks = ["${base}", [${links}]];\` 200`,
    "\t}",
  ];
  out.push(
    "\t# Dashboard app tiles (CasaOS, Umbrel) open the server's LAN address:port.",
    "\t# CasaOS's /js/custom.js (and Umbrel's /tile-links.js) load this map and",
    "\t# send tiles to their public address instead.",
    "\t@casaos_tiles path /js/custom.js /_domains/app-links.js",
    "\theader @casaos_tiles >Cache-Control no-store",
    ...tileMap,
    "",
  );
  for (const r of paths) {
    const p = r.path;
    out.push(`\t# ${commentSafe(r.name)}`, ...noteLines(r, "\t"));
    if (r.type === "redirect") {
      out.push(`\t# ${p}/<rest> -> ${r.target}/<rest>`, `\tredir ${p} ${r.target}/ 302`, `\thandle_path ${p}/* {`, `\t\tredir ${r.target}{uri} 302`, "\t}");
    } else if (r.strip_prefix) {
      out.push(`\t# App has no base-URL setting: ${p} is stripped before proxying`, `\tredir ${p} ${p}/ 308`, `\thandle_path ${p}/* {`, ...backendLines(r.backend, 2), "\t}");
    } else {
      const m = "@route_" + p.replace(/^\/+|\/+$/g, "").replace(/[^A-Za-z0-9]/g, "_");
      out.push(`\t# App's base-URL setting must be ${p}`, `\t${m} path ${p} ${p}/*`, `\thandle ${m} {`, ...backendLines(r.backend, 2), "\t}");
    }
    out.push("");
  }
  out.push(`\t# Everything else -> ${commentSafe(cfg.fallback.name)}`, "\thandle {", ...backendLines(cfg.fallback.backend, 2), "\t}", "}");
  for (const r of routes.filter((r): r is SubdomainRoute => r.type === "subdomain").sort((a, b) => a.host.localeCompare(b.host))) {
    const dns = coveredByWildcard(r.host, base) ? "A + AAAA via the wildcard record" : "needs its own DNS record";
    out.push("", `# ${commentSafe(r.name)}. DNS-only (grey cloud), ${dns}.`, ...noteLines(r, ""));
    if (r.redirect_to) {
      out.push(`# Everything here redirects to ${r.redirect_to}, keeping the path.`, `${r.host} {`, "\timport common", `\tredir ${r.redirect_to}{uri} 302`, "}");
      continue;
    }
    if (r.xmpp) {
      out.push(...xmppSiteLines(r, r.xmpp, tileMap));
      continue;
    }
    out.push(`${r.host} {`, "\timport common");
    out.push("", "\t# App-tile map for dashboards served here (see the base domain block).", "\theader /_domains/app-links.js >Cache-Control no-store", ...tileMap);
    (r.extra_paths ?? []).forEach((x, i) => {
      const note = x.note ? wrap(x.note, 76).map((l) => `\t# ${commentSafe(l)}`) : [];
      out.push("", ...note, `\t@extra_${i} path ${x.paths.join(" ")}`, `\thandle @extra_${i} {`, ...backendLines(x.backend, 2), "\t}");
    });
    if (r.only_paths?.length) {
      out.push(
        "",
        "\t# Only these paths are published; everything else is a 404.",
        `\t@published path ${r.only_paths.join(" ")}`,
        "\thandle @published {",
        ...backendLines(r.backend, 2),
        "\t}",
        "",
        "\thandle {",
        "\t\trespond 404",
        "\t}",
      );
    } else out.push("", "\thandle {", ...backendLines(r.backend, 2), "\t}");
    out.push("}");
  }
  return out.join("\n") + "\n";
}

/**
 * A chat server's web address. XMPP itself never goes through Caddy (apps connect straight to
 * the client port, other servers to the federation port); this block exists so Caddy holds a
 * certificate for the domain, which Gluon copies into the chat server, and to front its HTTP side.
 */
function xmppSiteLines(r: SubdomainRoute, x: XmppSettings, tileMap: string[]): string[] {
  const h = r.host;
  const ports = [`${r.backend.port}`, ...(x.s2s_port ? [`other servers to ${x.s2s_port}`] : [])].join(" and ");
  const out = [
    `# Chat apps connect straight to port ${ports}, not through Caddy.`,
    "# Caddy holds the certificate Gluon copies into the chat server.",
    `${h} {`,
    "\timport common",
    "",
    "\t# App-tile map for dashboards served here (see the base domain block).",
    "\theader /_domains/app-links.js >Cache-Control no-store",
    ...tileMap,
    "",
  ];
  if (x.http_port) {
    const bosh = `https://${h}/http-bind`;
    const ws = `wss://${h}/xmpp-websocket`;
    out.push(
      "\t# Web chat apps look up the connection endpoints here (XEP-0156).",
      "\t@xmpp_discovery path /.well-known/host-meta /.well-known/host-meta.json",
      '\theader @xmpp_discovery Access-Control-Allow-Origin "*"',
      "\thandle /.well-known/host-meta {",
      '\t\theader Content-Type "application/xrd+xml; charset=utf-8"',
      `\t\trespond \`<?xml version='1.0' encoding='utf-8'?><XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'><Link rel='urn:xmpp:alt-connections:xbosh' href='${bosh}'/><Link rel='urn:xmpp:alt-connections:websocket' href='${ws}'/></XRD>\` 200`,
      "\t}",
      "\thandle /.well-known/host-meta.json {",
      '\t\theader Content-Type "application/json"',
      `\t\trespond \`{"links":[{"rel":"urn:xmpp:alt-connections:xbosh","href":"${bosh}"},{"rel":"urn:xmpp:alt-connections:websocket","href":"${ws}"}]}\` 200`,
      "\t}",
      "",
      "\t# BOSH, WebSocket and file uploads: the chat server's own web port.",
      "\thandle {",
      ...backendLines({ host: r.backend.host, port: x.http_port, tls: false }, 2),
      "\t}",
    );
  } else {
    out.push(
      "\thandle {",
      '\t\theader Content-Type "text/plain; charset=utf-8"',
      `\t\trespond "${h} is a chat server. Sign in with any XMPP app as you@${h}." 200`,
      "\t}",
    );
  }
  out.push("}");
  return out;
}

// ---------------------------------------------------------------- validation

const HOST_RE = /^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/;
const LABEL_RE = /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$/;
const IPV4_RE = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/;
const PATH_RE = /^\/[A-Za-z0-9._~-]+(\/[A-Za-z0-9._~-]+)*$/;
const MATCH_RE = /^\/[A-Za-z0-9._~/-]*\*?$/;
const URL_RE = /^https?:\/\/[A-Za-z0-9.-]+(:\d{1,5})?(\/[A-Za-z0-9._~%/-]*)?$/;

const CONTAINER_RE = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$/;
const DIR_RE = /^(\/[A-Za-z0-9._-]+)+$/;
export const PROSODY_CERT_DIR = "/etc/prosody/certs";

function invalid(message: string, routeId?: string, field?: string): never {
  throw new AppError("invalid_route", message, 400, { route: routeId, field });
}

function cleanBackend(b: Partial<Backend> | undefined, rid: string): Backend {
  if (!b) invalid("Choose which app this goes to.", rid, "port");
  const host = String(b.host || THIS_SERVER).trim().toLowerCase();
  const ip = host.match(IPV4_RE);
  if (!(host === THIS_SERVER || HOST_RE.test(host) || LABEL_RE.test(host) || (ip && ip.slice(1).every((o) => Number(o) < 256)))) {
    invalid(`“${host}” isn't a valid backend host.`, rid, "backend_host");
  }
  const port = Number(b.port);
  if (!Number.isInteger(port) || port < 1 || port > 65535) invalid("Backend port must be between 1 and 65535.", rid, "port");
  return { host, port, tls: !!b.tls };
}

function cleanPort(v: unknown, rid: string, field: string, label: string): number | null {
  if (v === null || v === undefined || v === "") return null;
  const port = Number(v);
  if (!Number.isInteger(port) || port < 1 || port > 65535) invalid(`${label} must be between 1 and 65535.`, rid, field);
  return port;
}

function cleanXmpp(raw: Record<string, unknown>, backend: Backend, rid: string): XmppSettings {
  const s2s = cleanPort(raw.s2s_port, rid, "s2s_port", "The federation port");
  const httpPort = cleanPort(raw.http_port, rid, "http_port", "The chat server's web port");
  if (httpPort !== null && httpPort === backend.port) invalid("The web port can't be the same as the port chat apps connect to.", rid, "http_port");
  if (s2s !== null && s2s === backend.port) invalid("The federation port can't be the same as the port chat apps connect to.", rid, "s2s_port");
  if (s2s !== null && httpPort !== null && s2s === httpPort) invalid("The web port can't be the same as the federation port.", rid, "http_port");
  let sync: XmppSettings["cert_sync"] = null;
  const cs = raw.cert_sync as Record<string, unknown> | null | undefined;
  if (cs && typeof cs === "object") {
    const container = String(cs.container ?? "").trim();
    const dir = String(cs.dir ?? PROSODY_CERT_DIR).trim().replace(/\/+$/, "") || PROSODY_CERT_DIR;
    if (!CONTAINER_RE.test(container)) invalid("Choose which container runs the chat server.", rid, "cert_container");
    if (!DIR_RE.test(dir) || dir.split("/").includes("..")) invalid(`“${dir}” isn't a valid folder inside the container.`, rid, "cert_dir");
    sync = { container, dir };
  }
  return { s2s_port: s2s, http_port: httpPort, cert_sync: sync };
}

/** Validate a full config from the client. Base domain always comes from the stored config. */
export function cleanConfig(raw: { routes: unknown[]; fallback?: RoutesConfig["fallback"] }, current: RoutesConfig): RoutesConfig {
  const base = current.base_domain;
  const fb = raw.fallback ?? current.fallback;
  const cfg: RoutesConfig = {
    base_domain: base,
    fallback: { name: String(fb.name || "CasaOS").slice(0, 60), app: fb.app ?? null, backend: cleanBackend(fb.backend, "fallback") },
    routes: [],
  };
  const hosts = new Set<string>();
  const paths = new Set<string>();
  const ids = new Set<string>();
  for (const item of raw.routes) {
    const r = item as Record<string, unknown>;
    let rid = String(r.id ?? "");
    if (!/^[a-z0-9-]{1,40}$/.test(rid) || ids.has(rid)) rid = crypto.randomBytes(4).toString("hex");
    ids.add(rid);
    const name = String(r.name ?? "").trim().slice(0, 60);
    if (!name) invalid("Give the address a name.", rid, "name");
    const out: Record<string, unknown> = { id: rid, type: r.type, name, enabled: r.enabled !== false };
    const note = String(r.note ?? "").split(/\s+/).join(" ").trim().slice(0, 400);
    if (note) out.note = note;
    if (typeof r.app === "string" && /^[A-Za-z0-9._-]{1,80}$/.test(r.app)) out.app = r.app;
    if (r.type === "subdomain") {
      const host = String(r.host ?? "").trim().toLowerCase().replace(/\.$/, "");
      if (!HOST_RE.test(host)) invalid(`“${host || "(empty)"}” isn't a valid hostname.`, rid, "host");
      if (host === base) invalid(`${base} itself is handled by the path addresses.`, rid, "host");
      if (hosts.has(host)) invalid(`${host} is already used by another address.`, rid, "host");
      hosts.add(host);
      out.host = host;
      out.backend = cleanBackend(r.backend as Partial<Backend>, rid);
      let only = r.only_paths as unknown;
      if (typeof only === "string") only = only.replace(/,/g, " ").split(/\s+/);
      const onlyPaths = (Array.isArray(only) ? only : []).map((p) => String(p).trim()).filter(Boolean).slice(0, 20);
      for (const p of onlyPaths) if (!MATCH_RE.test(p)) invalid(`“${p}” isn't a valid path pattern. Use e.g. /rest/* or /api/health.`, rid, "only_paths");
      if (onlyPaths.length) out.only_paths = onlyPaths;
      const extras = Array.isArray(r.extra_paths) ? (r.extra_paths as Record<string, unknown>[]).slice(0, 10) : [];
      const cleanExtras: ExtraPaths[] = [];
      for (const x of extras) {
        const xp = (Array.isArray(x?.paths) ? x.paths : []).map((p) => String(p).trim()).filter(Boolean).slice(0, 20);
        if (!xp.length) continue;
        for (const p of xp) if (!MATCH_RE.test(p)) invalid(`“${p}” isn't a valid path pattern. Use e.g. /admin/* or /api/health.`, rid, "extra_paths");
        const xn = typeof x.note === "string" ? x.note.trim().slice(0, 500) : "";
        cleanExtras.push({ paths: xp, backend: cleanBackend(x.backend as Partial<Backend>, rid), ...(xn ? { note: xn } : {}) });
      }
      if (cleanExtras.length) out.extra_paths = cleanExtras;
      if (typeof r.redirect_to === "string" && r.redirect_to.trim()) {
        const target = r.redirect_to.trim().replace(/\/+$/, "");
        if (!URL_RE.test(target)) invalid("Redirect target must be a plain http(s):// address.", rid, "redirect_to");
        if (new URL(target).hostname.toLowerCase() === host) invalid("A domain can't redirect to itself.", rid, "redirect_to");
        out.redirect_to = target;
        delete out.only_paths;
        delete out.extra_paths;
      } else if (r.xmpp && typeof r.xmpp === "object") {
        out.xmpp = cleanXmpp(r.xmpp as Record<string, unknown>, out.backend as Backend, rid);
        // A chat server publishes its whole domain; path limits don't apply.
        delete out.only_paths;
        delete out.extra_paths;
      }
    } else if (r.type === "path" || r.type === "redirect") {
      const p = "/" + String(r.path ?? "").trim().replace(/^\/+|\/+$/g, "");
      if (!PATH_RE.test(p)) invalid("Paths can use letters, numbers and . _ ~ - (e.g. /photos).", rid, "path");
      if (paths.has(p.toLowerCase())) invalid(`${base}${p} is already used by another address.`, rid, "path");
      paths.add(p.toLowerCase());
      out.path = p;
      if (r.type === "path") {
        out.backend = cleanBackend(r.backend as Partial<Backend>, rid);
        out.strip_prefix = !!r.strip_prefix;
      } else {
        const target = String(r.target ?? "").trim().replace(/\/+$/, "");
        if (!URL_RE.test(target)) invalid("Redirect target must be a plain http(s):// address.", rid, "target");
        out.target = target;
      }
    } else invalid("Unknown address type.", rid);
    cfg.routes.push(out as unknown as Route);
  }
  return cfg;
}

// ---------------------------------------------------------------- admin socket

export class CaddyUnreachable extends AppError {
  constructor(detail: string) {
    super("caddy_unreachable", `Can't reach Caddy (${detail}). Is the proxy stack running?`, 502);
  }
}

export function caddyAdmin(method: string, urlPath: string, body?: string, contentType?: string): Promise<{ status: number; body: string }> {
  return new Promise((resolve, reject) => {
    const req = http.request(
      {
        socketPath: ADMIN_SOCKET,
        path: urlPath,
        method,
        // Caddy only accepts Host "", 127.0.0.1 or ::1 on unix-socket admin endpoints.
        headers: { Host: "127.0.0.1", ...(contentType ? { "Content-Type": contentType } : {}) },
        timeout: 60_000,
      },
      (res) => {
        let data = "";
        res.setEncoding("utf8");
        res.on("data", (c) => (data += c));
        res.on("end", () => resolve({ status: res.statusCode ?? 0, body: data }));
      },
    );
    req.on("error", (e) => reject(new CaddyUnreachable((e as NodeJS.ErrnoException).code ?? e.message)));
    req.on("timeout", () => req.destroy(new Error("timeout")));
    if (body) req.write(body);
    req.end();
  });
}

async function caddyLoad(caddyfile: string) {
  const r = await caddyAdmin("POST", "/load", caddyfile, "text/caddyfile");
  if (r.status !== 200) {
    let msg = r.body;
    try {
      msg = (JSON.parse(r.body) as { error?: string }).error ?? r.body;
    } catch {
      /* raw */
    }
    throw new AppError("caddy_rejected", `Caddy rejected the change: ${msg.trim().slice(0, 400)}`, 400);
  }
}

export async function caddyRunning(): Promise<boolean> {
  try {
    return (await caddyAdmin("GET", "/config/admin")).status === 200;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------- persistence

function ownLike(p: string) {
  try {
    const st = fs.statSync(/*turbopackIgnore: true*/ CADDY_DIR);
    fs.chownSync(p, st.uid, st.gid);
  } catch {
    /* best effort */
  }
}

function atomicWrite(file: string, text: string) {
  const tmp = `${file}.tmp-${process.pid}`;
  try {
    fs.writeFileSync(tmp, text, { mode: 0o644 });
    fs.chmodSync(tmp, 0o644);
    ownLike(tmp);
    fs.renameSync(tmp, file);
  } catch (e) {
    try {
      fs.unlinkSync(tmp);
    } catch {
      /* none */
    }
    throw e;
  }
}

function snapshot(reason: string): string {
  const stamp = new Date().toISOString().replace(/[-:]/g, "").replace(/\.(\d+)Z$/, "$1Z").replace("T", "T");
  const dir = path.join(HISTORY_DIR, stamp);
  fs.mkdirSync(dir, { recursive: true });
  for (const f of [ROUTES_FILE, CADDYFILE]) if (fs.existsSync(/*turbopackIgnore: true*/ f)) fs.copyFileSync(/*turbopackIgnore: true*/ f, path.join(dir, path.basename(f)));
  fs.writeFileSync(path.join(dir, "reason.txt"), reason);
  for (const p of [HISTORY_DIR, dir, ...fs.readdirSync(dir).map((f) => path.join(dir, f))]) ownLike(p);
  const all = fs.readdirSync(HISTORY_DIR).sort();
  for (const old of all.slice(0, Math.max(0, all.length - HISTORY_KEEP))) fs.rmSync(path.join(HISTORY_DIR, old), { recursive: true, force: true });
  return dir;
}

export function caddyfileDrift(cfg: RoutesConfig): boolean {
  try {
    return fs.readFileSync(CADDYFILE, "utf8") !== renderCaddyfile(cfg);
  } catch {
    return true;
  }
}

/** Push to Caddy first; persist only after Caddy accepted. Roll Caddy back if persisting fails. */
export async function applyConfig(cfg: RoutesConfig, reason: string): Promise<RoutesConfig> {
  const text = renderCaddyfile(cfg);
  await caddyLoad(text);
  let snap: string | null = null;
  try {
    snap = snapshot(reason);
    const saved = { ...cfg, updated: new Date().toISOString().slice(0, 19) + "Z" };
    atomicWrite(ROUTES_FILE, JSON.stringify(saved, null, 2) + "\n");
    atomicWrite(CADDYFILE, text);
    return saved;
  } catch (e) {
    try {
      await caddyLoad(fs.readFileSync(CADDYFILE, "utf8"));
    } catch {
      /* best effort */
    }
    if (snap) fs.rmSync(snap, { recursive: true, force: true });
    throw new AppError("persist_failed", `Couldn't save the routes file: ${(e as Error).message}. Nothing changed.`, 500);
  }
}

export interface HistoryEntry {
  id: string;
  time: string;
  reason: string;
  hasRoutes: boolean;
}

export function listHistory(): HistoryEntry[] {
  if (!fs.existsSync(HISTORY_DIR)) return [];
  return fs
    .readdirSync(HISTORY_DIR)
    .sort()
    .reverse()
    .flatMap((d) => {
      const m = d.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})/);
      if (!m) return [];
      const dir = path.join(HISTORY_DIR, d);
      let reason = "";
      try {
        reason = fs.readFileSync(path.join(dir, "reason.txt"), "utf8").trim();
      } catch {
        /* none */
      }
      return [{ id: d, time: `${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`, reason, hasRoutes: fs.existsSync(path.join(dir, "routes.json")) }];
    });
}

export function readHistoryRoutes(id: string): RoutesConfig {
  if (!/^\d{8}T\d{6}\d*Z$/.test(id)) throw new AppError("not_found", "That snapshot is gone.", 404);
  const p = path.join(HISTORY_DIR, id, "routes.json");
  if (!fs.existsSync(p)) throw new AppError("not_found", "That snapshot is gone.", 404);
  return JSON.parse(fs.readFileSync(p, "utf8")) as RoutesConfig;
}

export function readCaddyfile(): string {
  return fs.readFileSync(CADDYFILE, "utf8");
}
